version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data_mu:/var/lib/mysql
     restart: unless-stopped
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     working_dir: /var/www/html
     volumes:
       - html:/var/www/html
       - etc:/etc
       - php:/usr/local/etc/php
     restart: unless-stopped
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
volumes:
    db_data_mu: {}
    html: {}
    etc: {}
    php: {}
